### ISSUE TITLE
Better logic to check volume value

### ISSUE THREAD

**Issue by sirinath** [Denn1Ro/MQL_Easy#12]
Following is a better way to check:

```mql5
   double volume_step = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);
   int ratio = (int) MathRound((volume - min_volume) / volume_step);
   double closest_volue = ratio * volume_step + min_volume;
   if(MathAbs(closest_volue - volume) >= 0.000000005)
     {
          ....
     }
```

This protects against incorrect results when `min_volume != volume_step`. Also since MT gives volume to 8 decimal for some asset classes places it is best to use `>= 0.000000005`.

**Comment by Denn1Ro** [comment]
The improvement is completed with the commit 728a0c8e9c797c18abd1c98f561bd010d024ead3

**Comment by sirinath** [comment]
Perhaps the error message can improve in light of the changed logic: `"Volume is not a multiple of the minimal step SYMBOL_VOLUME_STEP = "+(string)volumeStep+" plus minimum order volume SYMBOL_VOLUME_MIN = " + (string)minVolume + ", the closest correct volume is "+(string)(closestValue)`
