### ISSUE TITLE
Compilation errors with MT5 Build 2981

### ISSUE THREAD

**Issue by eromawyn** [Denn1Ro/MQL_Easy#5]
Hello,

I am giving a try to MQL_Easy, seems to be a convenient way to write EA compatible with both MT4 and MT5 (with help of mql4compat.mqh for indicators). So I wrote a test EA in MT4, which works (and looses money, but that’s another point).

However, when moving the EA to MQL5 (build 2981), I get the following compilation errors :

cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	OrderMT5.mqh	192	39
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	OrderMT5.mqh	336	32
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	OrderMT5.mqh	399	34

		   MqlTradeRequest request       = {0}; 
		   MqlTradeResult result         = {0};

I’m not a MQL5 expert, but I think it should be converted to : 

		   MqlTradeRequest request       = {}; 
		   MqlTradeResult result         = {};

Which I did, and same EA started working on MT5 (and still looses money, but no wonder here).

Same problems with files ExecuteMT5 and PositionMT5.

**Comment by AgimaFR** [comment]
You should use language constants rather than values.
https://www.mql5.com/en/docs/constants/tradingconstants/enum_trade_request_actions

**Comment by tkittich** [comment]
Hello,

I am new to MQL5 and just got the same errors with build 2021. The code is downloaded from https://www.mql5.com/en/code/25090 and not sure if that's the most updated version or not.

cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	ExecuteMT5.mqh	68	31
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	ExecuteMT5.mqh	117	31
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	PositionMT5.mqh	256	32
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	PositionMT5.mqh	440	38
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	PositionMT5.mqh	501	37
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	PositionMT5.mqh	573	34
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	OrderMT5.mqh	192	39
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	OrderMT5.mqh	336	32
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	OrderMT5.mqh	399	34
