### ISSUE TITLE
feature request: CPosition::GroupAverageVolume()

### ISSUE THREAD

**Issue by tkittich** [Denn1Ro/MQL_Easy#6]
Currently , if GROUP_POSITIONS type is not specified, GroupTotalVolume() sums all volumes of both Buy and Sell positions. It would be great to have a GroupAverageVolume() that would add Buy volumes and subtract Sell volumes. This average volume, together with GroupAverageOpenPrice(), would represent the average position.

**Comment by Denn1Ro** [comment]
Good point. Implementation is on the way!

**Comment by Denn1Ro** [comment]
The implementation is completed with the commit 29b430d16f712a0889a374806a009bd76b988d0e
