### ISSUE TITLE
feature request: CPosition::GroupAverageCurrentPrice()

### ISSUE THREAD

**Issue by tkittich** [Denn1Ro/MQL_Easy#7]
Hello,

It seems the open price POSITION_PRICE_OPEN could be different from the current price POSITION_PRICE_CURRENT. A GroupAverageCurrentPrice() would be great. 

Thank you.

**Comment by Denn1Ro** [comment]
The implementation is completed with commit 29b430d16f712a0889a374806a009bd76b988d0e
