### ISSUE TITLE
Change Printer::PrintContent

### ISSUE THREAD

**Issue by mhamri** [Denn1Ro/MQL_Easy#8]
at the moment the print message keep spamming even if there is nothing to print 

https://github.com/Denn1Ro/MQL_Easy/blob/a39fb3fc2ca33626f8007adf044f73a071161b17/MQL_Easy/Printer/Printer.mqh#L217

a check like this could helps alot 

```C
void CPrinter::PrintContent(void)
{
   string keys[];
   string values[];
   this.KeyValue.GetAllKeys(keys);
   this.KeyValue.GetAllValues(values);
   if (ArraySize(values) == 0)
   {
      return;
   }
   Print(this.Container + this.Title + this.Container);
   int size = ArraySize(keys);
   for (int i = 0; i < size; i++)
   {
      Print(keys[i] + this.SeparatorKeyValue + values[i]);
   }
   Print(this.Container + this.Title + this.Container);
   this.KeyValue.Clear();
}
```

**Comment by mhamri** [comment]
later if I have time, I will make a PR

**Comment by Denn1Ro** [comment]
The implementation is completed. with the commit 29b430d16f712a0889a374806a009bd76b988d0e
