### ISSUE TITLE
Feature request: async orders

### ISSUE THREAD

**Issue by tkittich** [Denn1Ro/MQL_Easy#9]
Hello,

It would be great to have async orders and async close by using OrderSendAsync(). Currently, the library use normal OrderSend() which wait for the result. The speed of async orders are much much faster than the normal ones.

**Comment by Denn1Ro** [comment]
Hi, 
Thank you for your proposal. 
I will make update about this implementation. 
Regards

**Comment by Denn1Ro** [comment]
It is done. Feel free to check it.

**Comment by Heart1010** [comment]
Is OrderSendAsync() working also for MT4?

**Comment by sirinath** [comment]
I don't think this should be available for MT4.

**Comment by Heart1010** [comment]
so MQL_Easy is checking that and don't use it for MT4?

**Comment by Denn1Ro** [comment]
The MT4 doesn't support to send async trades as the MT5 does. So there is no way to implement in MT4. Due to compatibility with MT5, when you use the PositionAsync in MT4, it going to use the synchronous function OrderSend which the Position function use.
